### ISSUE TITLE
The domain parameter for NewConverter

### ISSUE THREAD

**Issue by suntong** [JohannesKaufmann/html-to-markdown#22] opened 2020-07-26 22:28 UTC
> `domain` is used for links and images to convert relative urls ("/image.png") to absolute urls.

However, I found it not working:

```go
package main

import (
	"fmt"
	"log"

	md "github.com/JohannesKaufmann/html-to-markdown"

	"github.com/PuerkitoBio/goquery"
)

func main() {
	url := "https://github.com/JohannesKaufmann/html-to-markdown"
	doc, err := goquery.NewDocument(url)
	if err != nil {
		log.Fatal(err)
	}
	content := doc.Find("div.BorderGrid-row.hide-sm.hide-md > div")

	conv := md.NewConverter(md.DomainFromURL(url), true, nil)
	markdown := conv.Convert(content)

	fmt.Println(markdown)
}
```

```sh
go run /tmp/h2m-test.go
## About

_ Convert HTML to Markdown. Even works with whole websites.


### Topics

[go](/topics/go "Topic: go")[golang](/topics/golang "Topic: golang")[html](/topics/html "Topic: html")[html-to-markdown](/topics/html-to-markdown "Topic: html-to-markdown")[markdown](/topics/markdown "Topic: markdown")

### Resources

[Readme](#readme)

### License

[MIT License](/JohannesKaufmann/html-to-markdown/blob/master/LICENSE)
```

I.e., none of links and images are converted from relative urls ("/image.png") to absolute urls.

**Comment by JohannesKaufmann** [comment] 2020-07-27 09:08
@suntong yeah you are totally right. I should have taken care of it sooner. I will work on it in the next couple of days.

I will probably also add a function to the options where you can configure the image and link urls. For example rewriting the url. 

Duplicate of #2

**Comment by JohannesKaufmann** [comment] 2020-08-06 17:16
@suntong this should now be fixed in the latest version as well.

You can now override the `GetAbsoluteURL` function in the `Options`. For example, you can configure a proxy for the images. But the default function now properly handles relative links.

Let me know if anything does not work!

**Closed by JohannesKaufmann** 2020-08-06 17:16 UTC
